### ISSUE TITLE
OSS公開に向けたタスク

### ISSUE THREAD

**Issue by kazuki** [penguin-judge/PenguinJudge#155]
* ライセンス周り
    * [ ] ライセンスの決定とライセンスファイルの配置
        * AGPL3.0: @kazuki 
        * MIT/修正BSD: 
        * 何でも良い: @iwashi (GPLとかじゃなければ)
    * [ ] AUTHORSファイルの作成
* [ ] 公開するアカウントや場所の決定
    * 新規にOrgを作ってそこで公開: @kazuki @iwashi
        * Org名リポジトリ名ともに PenguinJudge かな？
* [ ] コミットログは全部消すかどうか
    * 消さなくても良い派: @kazuki 
    * 消したほうが良い派: 
    * どちらでも良い派: @iwashi

**Comment by iwashi** [comment]
これ閉じて良さそ〜

**Comment by kazuki** [comment]
ライセンスファイルをリポジトリに登録後にクローズします。BSDライク系にしますか〜

**Comment by iwashi** [comment]
よさそうですー

**Comment by kazuki** [comment]
念の為、直接依存するパッケージのライセンスを確認したところ、
* BSD/MITライセンス
* Apacheライセンス
* LGPL (psycopg2-binary のみ)
でした
