### ISSUE TITLE
ジャッジ待ち・ジャッジ中の提出がある場合の順位表上の挙動

### ISSUE THREAD

**Issue by rsm9** [penguin-judge/PenguinJudge#182]
コンテスト中の提出について、ジャッジ結果が出るまでの間、順位表上ではペナルティと同様に扱われているようです（ACが得られる提出であったとしても、ACと判定されるまでは順位表ではペナルティとしてカウントされる）。

Contestantはリアルタイムな順位表の情報を基に提出のタイミングを計ることもあるため、ジャッジ結果が出るまでの順位表上の挙動について修正を施したいです。案としては

- ひとまずこれらの提出をペナルティ計算に反映されないようにする（優先度：高）
- それに加え、更にジャッジ待ちであることを示す別の記号（例：砂時計のアイコン等？ ）を表示させる

があります。

後者の案のイメージ
![fig](https://user-images.githubusercontent.com/32937551/83037221-7fdd0e00-a076-11ea-9967-0f1d30f81d1c.PNG)

**Comment by kazuki** [comment]
バグですね〜　報告ありがとうございます！

どちらの対応も可能なのですが、どっちのほうが良いですかね…

**Comment by rsm9** [comment]
後者は無いよりはあった方が便利な機能だと（個人的には）思いますが、この機能がないコンテストサイトも世の中にはたくさんあるので、設計方針の問題かもしれません…。

とりあえず前者の対処だけでもよいかもです
