### ISSUE TITLE
入出力の形式をAtCoder or AOJ 準拠にしたい

### ISSUE THREAD

**Issue by shiodat** [penguin-judge/PenguinJudge#184]
- RIME が公式にサポートしているJudgeSystemプラグインはAtCoder/AOJ/HackerRankです。
    - https://github.com/icpc-jag/rime/tree/master/rime/plugins/judge_system
    - AtCoderは入力フォルダを`in`、出力フォルダを`out`、その他を`etc`に格納し、入出力のファイルには特に拡張子は設定しません。
    - AOJは入力フォルダを`in`、出力フォルダを`out`に格納し、入出力ファイルには`.txt`を付けます。
- `$ rime pack` コマンドで問題を固められるのですが、PenguinJudgeにアップロードする際には、PenguinJudge専用のプラグインを使う必要があります。
    - https://github.com/shiodat/rime/blob/master/rime/plugins/judge_system/penguin.py
- RIMEは現在も開発が続いていますので、AtCoder or AOJ にジャッジシステム側を準拠させたほうが、RIMEを使い続けやすくて良いと思います。
    - 内部事情ですが、RIMEを使ったWorkshopをする際に公式のRIMEを使えるほうが良い、というのもあります。

**Comment by kazuki** [comment]
前回リリース (v1.1) に対応しようとして、見送った項目ですよね。

内部ワークショップまでに対応したいと思います！

**Comment by shiodat** [comment]
> AtCoder / AOJ どちらのほうが良いと思います？特

AOJ の仕様を勘違いしていました… AOJ の方は In / Out を同じフォルダに出力する & 問題がリネームされてしまう事に気づきました。AtCoder準拠にしていただくと in/out 別フォルダで出力されるので、🐧  の改修コストが少なくて良いと思います。

AOJ / AtCoder 両方で `$ rime pack` コマンドを打った結果です。
https://gist.github.com/shiodat/743bd5df4a515a74db69cdafa2964271

また、RIMEでプロジェクトを初期化するとAtCoderプラグインを読みにいくようになっているので、AtCoder準拠のほうがユーザが使いやすいかと思います。

```
$ rime_init --git
Initialized empty Git repository in ***
[master (root-commit) 9d6f92b] Initial commit
 3 files changed, 5040 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 PROJECT
 create mode 100644 common/testlib.h

$ cat PROJECT
# -*- coding: utf-8; mode: python -*-

## You can load plugins here.
use_plugin('rime_plus')
use_plugin('judge_system.atcoder')  # AtCoderプラグインが標準で利用される
#use_plugin('judge_system.aoj')
#use_plugin('judge_system.hacker_rank')
#use_plugin('wikify')
#use_plugin('wikify_full')
...
```

**Comment by shiodat** [comment]
AtCoder準拠の改善をしていたのですが、PenguinJudge用のプラグインを整備したほうが良い気がしてきました。理由は以下です。

- `$ rime pack` コマンドを打ってもREADME.mdは格納されない。そのため、PenguinJugdeプラグインでREADMEも入出力一式と合わせて1つのフォルダにまとめられるようにしたほうが便利。
- adminの問題画面の `テスト用入出力セット` で入出力をブラウザからダウンロードできるようになっていますが、AtCoder準拠にしてしまうと `.in`, `.out` 拡張子がつかなくなってしまい、ダウンロードしたファイルの入出力の区別がつかなくなってしまう。

**Comment by kazuki** [comment]
penguin-judge/rime#1 マージしました。

rime upload 対応も実施し、対応後にクローズします

**Comment by kazuki** [comment]
内部ディスカッションより、以下のようにrimeのPROBLEMを記述して、
問題の各種制約も設定できるようにすることになりました。

```
problem(
  time_limit=5,
  id='A',
  title='テスト問題: Penguin Judge へようこそ！',
  reference_solution='sample_solution',
)
penguin_config(
  memory_limit=512,
  score=100,
)
```

**Comment by kazuki** [comment]
と思ったが、内部では問題をGitHubで管理しているため、
便宜上 README.md にタイトルと各種制約を記載しており、GitHubのMarkdownプレビューでREADMEを表示するだけで、タイトル・各種制約が表示できた (詳細は tools/register_contest.py を参照)

* 案1: rimeのPROBLEMにタイトルと各種制約を記述し、問題文ファイル(README.md)には問題文のみを記載するようにする
   * メリット
      * 重複管理するデータがなくなる、README.mdをパースする必要がないので安定的に各種制約を読み込める
   * デメリット
      * 問題文をGitHubで管理しているがREADME.mdからタイトルと制約がなくなるので、README.mdを開いただけではタイトルすらわからない
      * PenguinJudge以外に問題を使う場合はPROBLEMを修正する必要がある(penguin_configという関数を使うため。とはいえ、atcoderに対応する際も修正は必要なので気にしなくてもよいかも)

* 案2: rime upload時にREADME.mdに記載のタイトルと制約をパースする機能を実装する
   * メリット
      * 案1のデメリットのGitHubプレビュー時の問題が発生しない
      *  PenguinJudge以外を利用する場合もPROBLEMを修正しなくてもよい
   * デメリット
      * タイトルと時間制約が二重管理(README.md, PROBLEM)になる
      * README.mdの記述に制約が生じる (1行目にタイトル、2行目に 実行時間制限: 5 sec / メモリ制限: 1024 MB / 配点: 100点 ) を書く。みたいな制約。

**Comment by kazuki** [comment]
#191 penguin-judge/rime#2 で対応
