### ISSUE TITLE
フロントエンド・ユーザ情報（変更）

### ISSUE THREAD

**Issue by mikikusu** [penguin-judge/PenguinJudge#28]
ユーザ情報として、以下の表示と変更できる画面があると良い。
* ログインID（これは変更不可でも良い気がする）
* 表示名（ログインIDを変更可能にするなら、そっちに一元化しても良い）
* 所属（今回のコンテスト考えるとあると便利）
* パスワード

ログインIDは重複不可、表示名も重複不可かな。

**Comment by kazuki** [comment]
ユーザIDはメアド等とし、ランキングには表示名を使うようにするため、
この昨日の実装が必要。マイルストーンを設定。
